//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userdetailshandson
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int DetID { get; set; }
        public int UserID { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public string City { get; set; }
        public Nullable<int> ReportingTo { get; set; }
    
        public virtual LOGININFO LOGININFO { get; set; }
    }
}
